{% set name = "mctc-lib" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/grimme-lab/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c0b3ed75546ca6382f18b5569ce3f80c916537aaf02b208662bce6eb53338350

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ stdlib('c') }}    # [unix]
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib('m2w64_c') }}    # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - meson !=1.8.0
    - ninja
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - jonquil
    - toml-f

test:
  requires:
    - pkg-config
  commands:
    - pkg-config {{ name }} --exact-version {{ version }}
    - test -f $PREFIX/lib/lib{{ name }}$SHLIB_EXT  # [unix]
    - mctc-convert --help

about:
  home: https://github.com/grimme-lab/mctc-lib
  license: Apache-2.0
  license_file:
    - LICENSE
  summary: >-
    Modular computation tool chain library
  description: >-
    Common tool chain to molecular structure data in various applications. This library provides a unified way to perform operations on molecular structure data, like reading and writing to common geometry file formats.
  doc_url: https://grimme-lab.github.io/mctc-lib

extra:
  recipe-maintainers:
    - awvwgk
