{% set name = "mctc-lib" %}
{% set version = "0.4.1" %}
{% set fortran_abi = fortran_abi or "gcc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/grimme-lab/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e67b7c97ed4d53f0412ac9be4655c90bee720080089fe661298656f5a7bd4479

build:
  number: 1
  script:
    - set -ex  # [unix]
    - >
       meson setup _build
       ${MESON_ARGS:---prefix=${PREFIX} --libdir=lib}  # [unix]
       --prefix=%LIBRARY_PREFIX% --libdir=lib -Djson=disabled  # [win]
    - meson compile -C _build
    - meson test -C _build --no-rebuild --print-errorlogs  # [build_platform == target_platform]
    - meson install -C _build --no-rebuild

  string: {{ fortran_abi }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}

  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }} {{ fortran_abi }}_*

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ stdlib('c') }}    # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib('m2w64_c') }}    # [win]
    - {{ compiler('fortran') }}        # [fortran_abi == "gcc" and unix]
    - {{ compiler('m2w64_fortran') }}  # [fortran_abi == "gcc" and win]
    - ifx_linux-64                     # [fortran_abi == "ifx" and linux and x86_64]
    - ifx_win-64                       # [fortran_abi == "ifx" and win and x86_64]
    - meson
    - ninja
    - llvm-openmp  # [osx]
    - libgomp  # [linux]

test:
  requires:
    - pkg-config
  commands:
    - pkg-config {{ name }} --exact-version {{ version }}
    - test -f $PREFIX/lib/lib{{ name }}$SHLIB_EXT  # [unix]
    - mctc-convert --help

about:
  home: https://github.com/grimme-lab/mctc-lib
  license: Apache-2.0
  license_file:
    - LICENSE
  summary: >-
    Modular computation tool chain library
  description: >-
    Common tool chain to molecular structure data in various applications. This library provides a unified way to perform operations on molecular structure data, like reading and writing to common geometry file formats.
  doc_url: https://grimme-lab.github.io/mctc-lib

extra:
  recipe-maintainers:
    - awvwgk
