{% set name = "mctc-lib" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/grimme-lab/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b18b06f80e6274b353dd091c12b3a83217033ce0bd80471b54cf486cc60c0251

build:
  number: 2
  script:
    - set -ex  # [unix]
    - >
       meson setup _build
       ${MESON_ARGS:---prefix=${PREFIX} --libdir=lib}  # [unix]
       --prefix=%LIBRARY_PREFIX% --libdir=lib -Djson=disabled  # [win]
    - meson compile -C _build
    - meson test -C _build --no-rebuild --print-errorlogs  # [build_platform == target_platform]
    - meson install -C _build --no-rebuild
    - rm $PREFIX/bin/mctc-convert  # [unix]
    - rm %LIBRARY_PREFIX%\bin\mctc-convert.exe  # [win]

  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("fortran") }}
    - meson
    - ninja
    - llvm-openmp  # [osx]
    - libgomp  # [linux]

test:
  requires:
    - pkg-config
  commands:
    - pkg-config {{ name }} --exact-version {{ version }}
    - test -f $PREFIX/lib/lib{{ name }}$SHLIB_EXT  # [unix]

about:
  home: https://github.com/grimme-lab/mctc-lib
  license: Apache-2.0
  license_file:
    - LICENSE
  summary: >-
    Modular computation tool chain library
  description: >-
    Common tool chain to molecular structure data in various applications. This library provides a unified way to perform operations on molecular structure data, like reading and writing to common geometry file formats.
  doc_url: https://grimme-lab.github.io/mctc-lib

extra:
  recipe-maintainers:
    - awvwgk
