{% set name = "mctc-lib" %}
{% set version = "0.3.1" %}

package:
  name: {{ name }}-pkg
  version: {{ version }}

source:
  url: https://github.com/grimme-lab/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 03dc8ccba37413da70e55a07cef8e8de53bce33f5bb52c1f8db5fec326abe083

build:
  number: 1

outputs:
  - name: {{ name }}
    script: build_lib.sh  # [unix]
    script: build_lib.bat  # [win]

    build: 
      run_exports:
        - {{ pin_subpackage(name, max_pin='x.x') }}

    requirements:
      build:
        - {{ compiler('c') }}  # [unix]
        - {{ compiler('fortran') }}  # [unix]
        - {{ compiler('m2w64_c') }}  # [win]
        - {{ compiler('m2w64_fortran') }}  # [win]
        - meson
        - ninja
        - llvm-openmp  # [osx]
        - libgomp  # [linux]
      host:
        - json-fortran  # [unix]

    test:
      requires:
        - pkg-config
      commands:
        - pkg-config {{ name }} --exact-version {{ version }}
        - test -f $PREFIX/lib/lib{{ name }}$SHLIB_EXT  # [unix]
        - if not exist %LIBRARY_PREFIX%\\bin\\{{ name }}.dll exit 1  # [win]
        - if not exist %LIBRARY_PREFIX%\\lib\\{{ name }}.lib exit 1  # [win]
        - test ! -f $PREFIX/lib/lib{{ name }}.a  # [unix]
        - if exist %LIBRARY_PREFIX%\\lib\\{{ name }}.lib.a exit 1  # [win]
        - if exist %LIBRARY_PREFIX%\\lib\\{{ name }}.a exit 1  # [win]

  - name: mctc-convert
    script: build_app.sh  # [unix]
    script: build_app.bat  # [win]

    requirements:
      build:
        - {{ compiler('fortran') }}  # [unix]
        - {{ compiler('m2w64_fortran') }}  # [win]
        - pkg-config
        - asciidoctor  # [unix]
        - llvm-openmp  # [osx]
        - libgomp  # [linux]
      host:
        - {{ name }} =={{ version }}
      run:
        - {{ name }} =={{ version }}

    test:
      commands:
        - mctc-convert --version

about:
  home: https://github.com/grimme-lab/mctc-lib
  doc_url: https://grimme-lab.github.io/mctc-lib
  license: Apache-2.0
  license_file:
    - LICENSE
  summary: Modular computation tool chain library
  description: >-
    Common tool chain to molecular structure data in various applications. This library 
    provides a unified way to perform operations on molecular structure data, like reading
    and writing to common geometry file formats.

extra:
  recipe-maintainers:
    - awvwgk
  feedstock-name: {{ name }}
